ifeq ($(TARGET_ARCH),x86_64)
	TARGET_CPU_ABI := x86_64
	TARGET_ARCH := x86_64
	TARGET_ARCH_VARIANT := x86_64

	TARGET_NATIVE_BRIDGE_ARCH := arm64
	TARGET_NATIVE_BRIDGE_ARCH_VARIANT := armv8-a
	TARGET_NATIVE_BRIDGE_CPU_VARIANT := generic
	TARGET_NATIVE_BRIDGE_ABI := arm64-v8a
else
	TARGET_ARCH := arm64
	TARGET_ARCH_VARIANT := armv8-a
	TARGET_CPU_VARIANT := generic
	TARGET_CPU_ABI := arm64-v8a
endif

include build/make/target/board/BoardConfigGsiCommon.mk

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_RESERVED_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 16777216
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

DEVICE_MANIFEST_FILE += device/reaos/manifest.xml

